# Generated by Django 4.2.2 on 2023-06-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permission_level",
            field=models.IntegerField(default=0, verbose_name=range(0, 2)),
        ),
    ]
