# Generated by Django 4.2 on 2024-07-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDefaultQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_quota', models.IntegerField(default=8)),
                ('mem_quota', models.IntegerField(default=16)),
                ('gpu_quota', models.IntegerField(default=1)),
                ('labname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'unique_together': {('labname',)},
            },
        ),
    ]
