# Generated by Django 4.2.3 on 2023-07-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_permission_level"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
