# Generated by Django 4.2 on 2025-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usergpuquotatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('original_groups', models.TextField(help_text='Comma-separated list of groups the user belonged to')),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
                ('deletion_reason', models.CharField(blank=True, help_text="Reason for deletion (e.g., 'expired', 'manual', 'admin action')", max_length=255, null=True)),
                ('deleted_by', models.CharField(blank=True, help_text='Username of admin who deleted this user', max_length=150, null=True)),
                ('additional_data', models.JSONField(blank=True, help_text='Additional user metadata stored as JSON', null=True)),
            ],
            options={
                'ordering': ['-deletion_date'],
            },
        ),
        migrations.AddField(
            model_name='groupdefaultquota',
            name='gpu_vendor',
            field=models.CharField(default='NVIDIA', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='deleteduser',
            index=models.Index(fields=['username'], name='api_deleted_usernam_8061da_idx'),
        ),
        migrations.AddIndex(
            model_name='deleteduser',
            index=models.Index(fields=['deletion_date'], name='api_deleted_deletio_6b8da1_idx'),
        ),
    ]
