# Generated by Django 4.2 on 2025-11-18 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_deleteduser_groupdefaultquota_gpu_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('removed_from_groups', models.TextField(help_text='Comma-separated list of groups user was removed from')),
                ('removal_date', models.DateTimeField(auto_now_add=True)),
                ('scheduled_deletion_date', models.DateTimeField(help_text='Date when user will be permanently deleted')),
                ('removal_reason', models.CharField(blank=True, help_text='Reason for group removal', max_length=255, null=True)),
                ('removed_by', models.CharField(blank=True, help_text='Admin who removed user from groups', max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_deletion_date'],
            },
        ),
        migrations.AddIndex(
            model_name='pendingdeletion',
            index=models.Index(fields=['username'], name='api_pending_usernam_db6856_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingdeletion',
            index=models.Index(fields=['scheduled_deletion_date'], name='api_pending_schedul_edb094_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingdeletion',
            index=models.Index(fields=['removal_date'], name='api_pending_removal_90def7_idx'),
        ),
    ]
