# Generated by Django 4.2 on 2025-11-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pendingdeletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupdefaultquota',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='群組到期日期', null=True),
        ),
    ]
